# Data transformation

```{r, echo=FALSE, warning=FALSE}
library(dplyr)
library(tidyverse)
library(countrycode)
```

```{r}
# Load Energy Data
df_energy_long <- read.csv("data/owid_energy_data.csv", header = TRUE, stringsAsFactors = FALSE)
df_energy_long <- df_energy_long %>% 
  select(-contains(c("_per_capita", "_pct", "_change", "_production", "_share"))) %>%
  subset(year >= 1990 & year <= 2019) %>%
  rename("ISO_code" = "iso_code") %>%
  subset(ISO_code != "") %>%
  rename("fossil_fuel" = "fossil_fuel_consumption", 
         "hydro" = "hydro_consumption", 
         "low_carb" = "low_carbon_consumption", 
         "nuclear" = "nuclear_consumption", 
         "other_renew" = "other_renewable_consumption", 
         "renew" = "renewables_consumption", 
         "solar" = "solar_consumption", 
         "wind" = "wind_consumption", 
         "coal" = "coal_consumption", 
         "gas" = "gas_consumption", 
         "oil" = "oil_consumption", 
         "biofuel" = "biofuel_consumption", 
         "primary" = "primary_energy_consumption") %>%
  select("ISO_code", "year", "fossil_fuel", "hydro", "low_carb", "nuclear", "other_renew", "renew", "solar", "wind", "coal", 
         "gas", "oil", "biofuel", "primary")

df_energy_ISO_with_no_missing_year <- df_energy_long %>%
  select("ISO_code", "year") %>%
  group_by(ISO_code) %>%
  summarize(count = n()) %>%
  filter(count == 2019 - 1990 + 1) %>%
  pull(ISO_code)

df_energy_long <- df_energy_long %>%
  filter(ISO_code %in% df_energy_ISO_with_no_missing_year)

# Choose years
relevant_years <- as.character(1990:2019)

# Load GDP Per Capita Data
df_GDP_wide <- read.csv("data/worldbank_GDP.csv", skip = 4, check.names = FALSE)
df_GDP_wide <- df_GDP_wide %>%
  select("Country Name", "Country Code", relevant_years) %>%
  rename("country" = "Country Name", "ISO_code" = "Country Code") %>%
  mutate_at(relevant_years, as.numeric) %>%
  select("ISO_code", relevant_years)
  

# Load Life Expectancy Data
df_life_wide <- read.csv("data/life_expectancy.csv", skip = 4, check.names = FALSE)
df_life_wide <- df_life_wide %>%
  select("Country Name", "Country Code", relevant_years) %>%
  rename("country" = "Country Name", "ISO_code" = "Country Code") %>%
  mutate_at(relevant_years, as.numeric) %>%
  select("ISO_code", relevant_years)

# Load Years of Schooling Data
df_schooling_wide <- read.csv("data/un_years_of_schooling.csv", skip = 6, check.names = FALSE)
df_schooling_wide <- df_schooling_wide %>%
  select("Country", relevant_years) %>%
  mutate("ISO_code" = countrycode(Country, origin = "country.name", destination = "iso3c")) %>%
  mutate_at(relevant_years, as.numeric) %>%
  select("ISO_code", relevant_years)

# Load population data
df_population_wide <- read.csv("data/population.csv", skip = 4, check.names = FALSE)
df_population_wide <- df_population_wide %>%
  select("Country Name", "Country Code", relevant_years) %>%
  rename("country" = "Country Name", "ISO_code" = "Country Code") %>%
  mutate_at(relevant_years, as.numeric) %>%
  select("ISO_code", relevant_years)

# Load HDI data
df_HDI_wide <- read.csv("data/HDI.csv", skip = 5, check.names = FALSE)
df_HDI_wide <- df_HDI_wide %>%
  select("Country", relevant_years) %>%
  mutate("ISO_code" = countrycode(Country, origin = "country.name", destination = "iso3c")) %>%
  mutate_at(relevant_years, as.numeric) %>%
  select("ISO_code", relevant_years)

# Load Country Info Data
df_country_info <- read.csv("data/worldbank_country_info.csv", header = TRUE, stringsAsFactors = FALSE, encoding = "UTF-8")
df_country_info <- as.data.frame(df_country_info) %>% 
  rename("ISO_code" = "X.U.FEFF.iso_code", "region" = "Region", "income_group" = "IncomeGroup", "special_notes" = "SpecialNotes")


# retrieve common countries across data sets based on ISO code
common_ISO_codes <- Reduce(intersect, list(df_energy_long$ISO_code,df_life_wide$ISO_code, df_schooling_wide$ISO_code, 
                                           df_GDP_wide$ISO_code, df_population_wide$ISO_code, df_HDI_wide$ISO_code))

# filter data sets on common ISO codes
df_energy_long <- df_energy_long %>% filter(ISO_code %in% common_ISO_codes)
df_GDP_wide <- df_GDP_wide %>% filter(ISO_code %in% common_ISO_codes)
df_life_wide <- df_life_wide %>% filter(ISO_code %in% common_ISO_codes)
df_schooling_wide <- df_schooling_wide %>% filter(ISO_code %in% common_ISO_codes)
df_population_wide <- df_population_wide %>% filter(ISO_code %in% common_ISO_codes)
df_HDI_wide <- df_HDI_wide %>% filter(ISO_code %in% common_ISO_codes)
```


```{r}
# Convert data frames to long format
df_GDP_long <- df_GDP_wide %>% pivot_longer(cols = -c("ISO_code"), names_to = "year", values_to = "GDP")
df_schooling_long <- df_schooling_wide %>% 
  pivot_longer(cols = -c("ISO_code"), names_to = "year", values_to = "years_of_schooling") %>%
  mutate_at("year", as.numeric)
df_life_long <- df_life_wide %>% pivot_longer(cols = -c("ISO_code"), names_to = "year", values_to = "life_expectancy")
df_population_long <- df_population_wide %>% pivot_longer(cols = -c("ISO_code"), names_to = "year", values_to = "population") 
df_HDI_long <- df_HDI_wide %>% pivot_longer(cols = -c("ISO_code"), names_to = "year", values_to = "HDI")
```


```{r}
# display number of rows for each dataframe
nrow(df_energy_long)
nrow(df_GDP_long)
nrow(df_life_long)
nrow(df_schooling_long)
nrow(df_population_long)
nrow(df_HDI_long)
```
```{r}
# merge data frames into one master data frame
master_df <- merge(df_energy_long, merge(df_GDP_long, merge(df_life_long, merge(df_schooling_long, merge(df_population_long, df_HDI_long,
                by = c("ISO_code", "year")), by = c("ISO_code", "year")), by = c("ISO_code", "year")), by = c("ISO_code", "year")), by = c("ISO_code", "year"))

# Add one variable for country name and reorder columns
master_df <- master_df %>%
  mutate(country = countrycode(ISO_code, origin = "iso3c", destination = "country.name")) %>%
  select(ISO_code, country, year, population, GDP, HDI, life_expectancy, years_of_schooling, everything())
```

```{r}
# write master_df to csv
write.csv(master_df,"data/master.csv", row.names = FALSE)
```

#TODOS:
- What countries are missing from the data set that exist in real life
- How many regions maximum compared to final dataset
- Make data cleaning steps more explicit
  - removing variables
  - limiting time frame
  - merge and exclude duplicates




