---
output:
  html_document: default
  pdf_document: default
---
# Missing values

```{r, echo=FALSE, warning=FALSE}
library(dplyr)
library(tidyverse)
library(patchwork)
library(Lock5withR)
library(ggpubr)

source("R/plot_missing_patterns.R")
```

## Energy consumption

```{r}
energy_data <- read.csv("data/owid_energy_data.csv", header=TRUE, stringsAsFactors=FALSE)
df_energy <- as.data.frame(energy_data)

selected_columns <- c("iso_code", "country", "year","consumption")
df_energy_sel <- df_energy %>% 
  select(contains(selected_columns)) %>%
  select(-contains(c("_per_capita", "_pct", "_change"))) %>%
  subset(year >= 1990) %>%
  rename("fossil_fuel" = "fossil_fuel_consumption", 
         "hydro" = "hydro_consumption", 
         "low_carb" = "low_carbon_consumption", 
         "nuclear" = "nuclear_consumption", 
         "other_renew" = "other_renewable_consumption", 
         "renew" = "renewables_consumption", 
         "solar" = "solar_consumption", 
         "wind" = "wind_consumption", 
         "coal" = "coal_consumption", 
         "gas" = "gas_consumption", 
         "oil" = "oil_consumption", 
         "biofuel" = "biofuel_consumption", 
         "primary" = "primary_energy_consumption")
  
plot_missing_parameters(df_energy_sel, use_counts = FALSE, max_100 = FALSE, 
                  ticks_angle = 45, ticks_size = 9, complete_cases_size = 3.5, complete_cases_hjust = 0)
```

## GDP per capita

```{r}
gdp_per_capita <- read.csv("data/gdp_per_capita.csv", skip = 4, check.names = FALSE)

relevant_years <- as.character(1990:2019)

gdp_per_capita <- gdp_per_capita %>%
  select("Country Name", relevant_years)

mygdp_per_capita <- gdp_per_capita
names(mygdp_per_capita) <- c("Country", substring(names(mygdp_per_capita)[1:length(relevant_years) + 1], 0, 4))

plot_missing_parameters(data = mygdp_per_capita, use_counts = FALSE, max_100 = FALSE, 
                        ticks_angle = 90, ticks_size = 7.5, complete_cases_size = 2, complete_cases_hjust = 0.05, y_ticks_size = 6)
```

## Life expectancy

```{r}
un_life_data <- read.csv("data/life_expectancy.csv", skip = 4, check.names = FALSE)

relevant_years <- as.character(1990:2019)

un_life_data <- un_life_data %>%
  select("Country Name", relevant_years)

myun_life_data <- un_life_data
names(myun_life_data) <- c("Country", substring(names(myun_life_data)[1:length(relevant_years) + 1], 0, 4))

plot_missing_parameters(data = myun_life_data, use_counts = FALSE, max_100 = FALSE, 
                        ticks_angle = 90, ticks_size = 7.5, complete_cases_size = 3, complete_cases_hjust = 0.05)
```

## Years of schooling

```{r}
un_years_of_schooling <- read.csv("data/un_years_of_schooling.csv", skip = 6, check.names = FALSE)

relevant_years <- as.character(1990:2019)

un_years_of_schooling <- un_years_of_schooling %>%
  select("Country", "HDI Rank", relevant_years) %>%
  mutate_at(relevant_years, as.numeric) %>%
  mutate_at("HDI Rank", as.numeric)

myun_years_of_schooling <- un_years_of_schooling
#names(myun_years_of_schooling) <- c("cy", "hdi", substring(names(myun_years_of_schooling)[1:length(relevant_years) + 1], 0, 4))

plot_missing_parameters(data = myun_years_of_schooling, use_counts = FALSE, max_100 = FALSE, 
                        ticks_angle = 90, ticks_size = 7.5, complete_cases_size = 3, complete_cases_hjust = 0.05)
```

