--- 
title: "Energy and Human Development"
author: "Antonin Vidon and Jannik Wiedenhaupt"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

The effect of energy consumption on economic growth is an important and long-existing area of research and teaches us that energy is one of the most important drivers of economic development. However, it is not only the economic development that relates to energy consumption but also broader human development. Considering the growing importance of different energy sources and the looming transition from fossil fuels to renewable energy sources, it is important to understand how energy consumption and human livelihood are related. In our study, we therefore examine human development and its core components, as collected in the human development indicator (HDI): A long and healthy life, the duration of education and the standard of living. This allows us to highlight potential misconceptions about the relationships between the development stages of countries and suggestions for policy-making.

**With this analysis we answer the following five questions**:

1. How is the increase in energy consumption boosting the education system in order to cope with the industrial ”boom” generated by rapid economic growth?
2. What are the most important factors that determine how a variation of energy consumption affects the human development index of a country?  
3. Is the rate at which the HDI increases with respect to energy consumption constant, or does it start to decrease after a specific GDP per capita?
4. Is a highly renewable energy mix associated with strong human development indicators?
5. What characterizes the countries that have the most renewable energy mix?  